-- PostgreSQL version of the project database
-- Converted from MySQL Workbench script

CREATE SCHEMA IF NOT EXISTS mydb;
SET search_path TO mydb;

-- -----------------------------------------------------
-- Remove as tabelas na ordem inversa das dependências
-- -----------------------------------------------------
DROP TABLE IF EXISTS roteiros_pontos_turisticos;
DROP TABLE IF EXISTS avaliacoes;
DROP TABLE IF EXISTS roteiros;
DROP TABLE IF EXISTS pontos_turisticos;
DROP TABLE IF EXISTS administradores;
DROP TABLE IF EXISTS usuarios;

-- -----------------------------------------------------
-- Table usuarios
-- -----------------------------------------------------
CREATE TABLE usuarios (
  idusuarios INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  token_recuperacao VARCHAR(255) NULL,
  token_expira_em TIMESTAMP NULL
);

-- -----------------------------------------------------
-- Table administradores
-- -----------------------------------------------------
CREATE TABLE administradores (
  idadmin INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  token_recuperacao VARCHAR(255) NULL,
  token_expira_em TIMESTAMP NULL
);

-- -----------------------------------------------------
-- Table pontos_turisticos
-- -----------------------------------------------------
CREATE TABLE pontos_turisticos (
  idpontos_turisticos INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  foto VARCHAR(500) NULL,
  descricao TEXT NULL,
  endereco VARCHAR(200) NULL,
  cidade VARCHAR(100) NULL,
  estado VARCHAR(100) NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------
-- Table avaliacoes
-- -----------------------------------------------------
CREATE TABLE avaliacoes (
  idavaliacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NOT NULL,
  ponto_id INT NOT NULL,
  nota INT NOT NULL,
  comentario TEXT NULL,
  data_avaliacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_avaliacoes_usuarios
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios (idusuarios)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_avaliacoes_pontos_turisticos
    FOREIGN KEY (ponto_id)
    REFERENCES pontos_turisticos (idpontos_turisticos)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CHECK (nota BETWEEN 1 AND 5)
);

-- -----------------------------------------------------
-- Table roteiros
-- -----------------------------------------------------
CREATE TABLE roteiros (
  idroteiro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'simples' CHECK (tipo IN ('simples', 'personalizado')),
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  usuario_id INT NULL,
  administrador_id INT NULL,
  CONSTRAINT fk_roteiros_usuarios
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios (idusuarios)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_roteiros_administradores
    FOREIGN KEY (administrador_id)
    REFERENCES administradores (idadmin)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- -----------------------------------------------------
-- Table roteiros_pontos_turisticos
-- -----------------------------------------------------
CREATE TABLE roteiros_pontos_turisticos (
  roteiro_id INT NOT NULL,
  ponto_id INT NOT NULL,
  ordem INT NOT NULL DEFAULT 1,
  PRIMARY KEY (roteiro_id, ponto_id),
  CONSTRAINT fk_roteiro_ponto_roteiro
    FOREIGN KEY (roteiro_id)
    REFERENCES roteiros (idroteiro)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_roteiro_ponto_ponto
    FOREIGN KEY (ponto_id)
    REFERENCES pontos_turisticos (idpontos_turisticos)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

GRANT USAGE ON SCHEMA mydb TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mydb TO anon, authenticated, service_role;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA mydb TO anon, authenticated, service_role;

-- -----------------------------------------------------
-- Usuários padrão do sistema
-- -----------------------------------------------------
INSERT INTO administradores (nome, email, senha) VALUES
  ('Administrador', 'admin@desbravando.com', 'e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7');

INSERT INTO usuarios (nome, email, senha) VALUES
  ('Renato', 'renato@email.com', 'fc3e25216432122f651655977976fccea1a96a3d1332afe9e98a6695979ea537'),
  ('Guilherme', 'guilherme@email.com', 'c735490be0e36270260474775bc0cf7ae5c82023ed215f1079b1d8d4229a638f');
